# dbt_project.yml
name: 'crypto_pipeline'
version: '1.0.0'
config-version: 2

profile: 'crypto_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target_path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    mart:
      +materialied: table