# models/sources.yml
version: 2

sources:
  - name: raw
    database: crypto_trading
    schema: main
    tables:
      - name: trades
        columns:
          - name: id
            description: "Trade ID"
            tests:
              - unique
              - not_null
          - name: price
            description: "Trade price"
          - name: qty
            description: "Trade quantity"
          - name: quoteQty
            description: "Quote currency quantity"
          - name: time
            description: "Trade timestamp"
          - name: isBuyerMaker
            description: "Whether buyer was the maker"
          - name: isBestMatch
            description: "Best match flag"
          - name: tick_volume
            description: "Computed: Trade volume"
          - name: tick_direction
            description: "Computed: Trade direction (-1, 0, 1)"
