# models/sources.yml
version: 2

sources:
  - name: raw
    tables:
      - name: trades
        # define using glob patterns
        external:
          location: "s3://crypto-pipeline-dev-data/raw/trades/{year}/{month}/{day}/btc-usdt_trades.csv"
          format: csv
          options:
            auto_detect: true
            filename: true
        columns:
          - name: id
            description: "Trade ID"
            tests:
              - unique
              - not_null
          - name: price
            description: "Trade price"
          - name: qty
            description: "Trade quantity"
          - name: quoteQty
            description: "Quote currency quantity"
          - name: time
            description: "Trade timestamp"
          - name: isBuyerMaker
            description: "Whether buyer was the maker"
          - name: isBestMatch
            description: "Best match flag"
          - name: tick_volume
            description: "Computed: Trade volume"
          - name: tick_direction
            description: "Computed: Trade direction (-1, 0, 1)"
