AWSTemplateFormatVersion: '2010-09-09'
Description: 'Crypto data pipeline infrastructure (Free Tier)'

Resources:
  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-data'
      VersioningConfiguration:
        Status: Enabled

  PipelineBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PipelineBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - !GetAtt PipelineBucket.Arn
                - '/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'

Outputs:
  BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref PipelineBucket